name: Deploy to GitHub Pages (Simple)

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create config.js from secrets
        run: |
          cat > config.js << 'EOF'
          // Конфигурация создается автоматически из секретов GitHub Actions
          window.GEMINI_CONFIG = {
            apiKey: '${{ secrets.GEMINI_API_KEY_1 }}',
            baseUrl: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent'
          };
          
          window.SUPABASE_CONFIG = {
            url: '${{ secrets.SUPABASE_URL }}',
            anonKey: '${{ secrets.SUPABASE_ANON_KEY }}'
          };
          EOF
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true 